### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by freddygl** [kristuff/abuseipdb-cli#29]
Hello, I have been using your tool for a year without problems, but since this morning I receive an error "An unexpected error occurred." and there is no way to make it work.
Any ideas?
Thank you so much.

**Comment by freddygl** [comment]
root@homebridge:/home/pi/ABUSEIPDB# abuseipdb -C 8.8.8.8

  ► Check IP: 8.8.8.8

   ERROR                                             
   ✗ Detail:    An unexpected error occurred.

  Request time: 0.08986496925354s | UTC time: 2023-06-12 09:28:15
  ------------------------------------------------------------------------------------------------------
  Kristuff\AbuseIPDB v0.9.20 | Made with ♥ in France | © 2020-2022 Kristuff (https://github.com/kristuff)

**Comment by kristuff** [comment]
It seems that the site has now the Cloudflare DDoS Mitigation.

I made a quick test and the problem is that the response to any api request is the temporary html page "Just a moment"

I didn't see related change in the api documentation so unfortunately, nothing I can do for now.(I just reported the issue on their site).

<img width="799" alt="apidb" src="https://github.com/kristuff/abuseipdb-cli/assets/16272398/5e5ed0b7-0921-4509-bcae-6215cbfe6a76">

**Comment by freddygl** [comment]
Hi.

it works again.

**Comment by kristuff** [comment]
Good to know :) Thank you
